markdown_extensions:
  - pycon

nav:
  - index.md
  - setup.md
  - Motivation:
    - motivation/railway-oriented-programming.md
    - motivation/trcks.md
  - usage.md
  - frequently-asked-questions.md
  - Reference:
      - reference/trcks.md
      - reference/trcks.fp.md
      - reference/trcks.fp.composition.md
      - reference/trcks.fp.monads.md
      - reference/trcks.fp.monads.awaitable.md
      - reference/trcks.fp.monads.awaitable_result.md
      - reference/trcks.fp.monads.identity.md
      - reference/trcks.fp.monads.result.md
      - reference/trcks.oop.md
      - reference/trcks.oop.AwaitableResultWrapper.md
      - reference/trcks.oop.AwaitableWrapper.md
      - reference/trcks.oop.ResultWrapper.md
      - reference/trcks.oop.Wrapper.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_section_style: list
            members_order: source
          paths:
            - src
  - search

repo_url: https://github.com/christophgietl/trcks

site_description: >
  trcks is a Python library.
  It allows railway-oriented programming (ROP) in two different programming styles:
  an object-oriented style based on method chaining and
  a functional style based on function composition.

site_name: trcks - Typesafe railway-oriented programming (ROP) in Python

site_url: https://christophgietl.github.io/trcks/

strict: true

theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    logo: material/directions-fork
  name: material
  palette:
    accent: teal
    primary: teal

validation:
  absolute_links: warn
  anchors: warn
  omitted_files: warn
  unrecognized_links: warn
