markdown_extensions:
  - pycon

nav:
  - index.md
  - trcks.fp.md
  - trcks.fp.composition.md
  - trcks.fp.monads.md
  - trcks.fp.monads.awaitable.md
  - trcks.fp.monads.awaitable_result.md
  - trcks.fp.monads.identity.md
  - trcks.fp.monads.result.md
  - trcks.oop.md
  - trcks.oop.AwaitableResultWrapper.md
  - trcks.oop.AwaitableWrapper.md
  - trcks.oop.ResultWrapper.md
  - trcks.oop.Wrapper.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_section_style: list
            members_order: source
          paths:
            - src
  - search

repo_url: https://github.com/christophgietl/trcks

site_description: Typesafe railway-oriented programming (ROP) in Python

site_name: trcks

site_url: https://christophgietl.github.io/trcks/

strict: true

theme:
  icon:
    logo: material/directions-fork
  name: material
  palette:
    accent: teal
    primary: teal

validation:
  absolute_links: warn
  anchors: warn
  omitted_files: warn
  unrecognized_links: warn
